
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.cut_block_type]

		[types.cut_block_type.ribbits]
			mossy_oak_planks = true

		[types.cut_block_type.botania]
			livingrock = true
			polished_livingrock = true
			livingrock_bricks = true
			mossy_livingrock_bricks = true
			livingwood = true
			stripped_livingwood = true
			livingwood_planks = true
			dreamwood = true
			stripped_dreamwood = true
			dreamwood_planks = true
			corporea_brick = true
			shimmerrock = true
			shimmerwood_planks = true
			dark_quartz = true
			mana_quartz = true
			blaze_quartz = true
			lavender_quartz = true
			red_quartz = true
			elf_quartz = true
			sunny_quartz = true
			white_pavement = true
			black_pavement = true
			blue_pavement = true
			yellow_pavement = true
			red_pavement = true
			green_pavement = true
			metamorphic_forest_stone = true
			metamorphic_forest_cobblestone = true
			metamorphic_forest_bricks = true
			metamorphic_plains_stone = true
			metamorphic_plains_cobblestone = true
			metamorphic_plains_bricks = true
			metamorphic_mountain_stone = true
			metamorphic_mountain_cobblestone = true
			metamorphic_mountain_bricks = true
			metamorphic_fungal_stone = true
			metamorphic_fungal_cobblestone = true
			metamorphic_fungal_bricks = true
			metamorphic_swamp_stone = true
			metamorphic_swamp_cobblestone = true
			metamorphic_swamp_bricks = true
			metamorphic_desert_stone = true
			metamorphic_desert_cobblestone = true
			metamorphic_desert_bricks = true
			metamorphic_taiga_stone = true
			metamorphic_taiga_cobblestone = true
			metamorphic_taiga_bricks = true
			metamorphic_mesa_stone = true
			metamorphic_mesa_cobblestone = true
			metamorphic_mesa_bricks = true

		[types.cut_block_type.the_bumblezone]
			ancient_wax_bricks = true
			ancient_wax_diamond = true
			ancient_wax_compound_eyes = true

		[types.cut_block_type.pneumaticcraft]
			reinforced_brick = true
			reinforced_stone = true
			compressed_brick = true
			compressed_stone = true

		[types.cut_block_type.ad_astra]
			iron_plating = true
			steel_plating = true
			desh_plating = true
			ostrum_plating = true
			calorite_plating = true
			moon_stone = true
			moon_cobblestone = true
			moon_stone_brick = true
			polished_moon_stone = true
			aeronos = true
			strophar = true
			mars_stone = true
			mars_cobblestone = true
			mars_stone_brick = true
			polished_mars_stone = true
			mercury_stone = true
			mercury_cobblestone = true
			mercury_stone_brick = true
			polished_mercury_stone = true
			venus_stone = true
			venus_cobblestone = true
			venus_stone_brick = true
			polished_venus_stone = true
			venus_sandstone_brick = true
			glacio_stone = true
			glacio_cobblestone = true
			glacio_stone_brick = true
			polished_glacio_stone = true
			permafrost_brick = true
			chiseled_permafrost_brick = true
			polished_permafrost = true
			glacian = true

		[types.cut_block_type.ars_nouveau]
			sourcestone = true
			sourcestone_mosaic = true
			sourcestone_basketweave = true
			sourcestone_alternating = true
			sourcestone_large_bricks = true
			sourcestone_small_bricks = true
			smooth_sourcestone_basketweave = true
			smooth_sourcestone_mosaic = true
			smooth_sourcestone_alternating = true
			smooth_sourcestone_large_bricks = true
			smooth_sourcestone = true
			smooth_sourcestone_small_bricks = true
			gilded_sourcestone_mosaic = true
			gilded_sourcestone_basketweave = true
			gilded_sourcestone_alternating = true
			gilded_sourcestone_large_bricks = true
			gilded_sourcestone_small_bricks = true
			smooth_gilded_sourcestone_mosaic = true
			smooth_gilded_sourcestone_basketweave = true
			smooth_gilded_sourcestone_alternating = true
			smooth_gilded_sourcestone_large_bricks = true
			smooth_gilded_sourcestone_small_bricks = true
			archwood = true

		[types.cut_block_type.redeco]
			polished_oak = true
			polished_spruce = true
			polished_birch = true
			polished_jungle = true
			polished_dark_oak = true
			polished_acacia = true
			polished_crimson = true
			polished_warped = true
			polished_mangrove = true
			polished_cherry = true
			polished_bamboo = true

		[types.cut_block_type.cataclysm]
			polished_end_stone = true
			purpur_tile = true
			polished_obsidian = true
			obsidian_brick = true
			chorus = true
			frosted_stone_brick = true
			stone_tile = true
			azure_seastone = true
			azure_seastone_brick = true
			polished_azure_seastone = true

		[types.cut_block_type.beachparty]
			thatch = true
			palm = true

		[types.cut_block_type.hearth_and_home]
			cobblestone_brick = true
			thatch = true
			polished_calcite = true
			shingle = true
			white_shingle = true
			orange_shingle = true
			magenta_shingle = true
			light_blue_shingle = true
			yellow_shingle = true
			lime_shingle = true
			pink_shingle = true
			gray_shingle = true
			light_gray_shingle = true
			cyan_shingle = true
			purple_shingle = true
			blue_shingle = true
			brown_shingle = true
			green_shingle = true
			red_shingle = true
			black_shingle = true
			terracotta_brick = true
			white_terracotta_brick = true
			orange_terracotta_brick = true
			magenta_terracotta_brick = true
			light_blue_terracotta_brick = true
			yellow_terracotta_brick = true
			lime_terracotta_brick = true
			pink_terracotta_brick = true
			gray_terracotta_brick = true
			light_gray_terracotta_brick = true
			cyan_terracotta_brick = true
			purple_terracotta_brick = true
			blue_terracotta_brick = true
			brown_terracotta_brick = true
			green_terracotta_brick = true
			red_terracotta_brick = true
			black_terracotta_brick = true
			tile = true
			white_tile = true
			orange_tile = true
			magenta_tile = true
			light_blue_tile = true
			yellow_tile = true
			lime_tile = true
			pink_tile = true
			gray_tile = true
			light_gray_tile = true
			cyan_tile = true
			purple_tile = true
			blue_tile = true
			brown_tile = true
			green_tile = true
			red_tile = true
			black_tile = true

		[types.cut_block_type.create]
			copper_shingle = true
			exposed_copper_shingle = true
			weathered_copper_shingle = true
			oxidized_copper_shingle = true
			waxed_copper_shingle = true
			waxed_exposed_copper_shingle = true
			waxed_weathered_copper_shingle = true
			waxed_oxidized_copper_shingle = true
			copper_tile = true
			exposed_copper_tile = true
			weathered_copper_tile = true
			oxidized_copper_tile = true
			waxed_copper_tile = true
			waxed_exposed_copper_tile = true
			waxed_weathered_copper_tile = true
			waxed_oxidized_copper_tile = true
			cut_granite = true
			polished_cut_granite = true
			cut_granite_brick = true
			small_granite_brick = true
			cut_diorite = true
			polished_cut_diorite = true
			cut_diorite_brick = true
			small_diorite_brick = true
			cut_andesite = true
			polished_cut_andesite = true
			cut_andesite_brick = true
			small_andesite_brick = true
			cut_calcite = true
			polished_cut_calcite = true
			cut_calcite_brick = true
			small_calcite_brick = true
			cut_dripstone = true
			polished_cut_dripstone = true
			cut_dripstone_brick = true
			small_dripstone_brick = true
			cut_deepslate = true
			polished_cut_deepslate = true
			cut_deepslate_brick = true
			small_deepslate_brick = true
			cut_tuff = true
			polished_cut_tuff = true
			cut_tuff_brick = true
			small_tuff_brick = true
			cut_asurine = true
			polished_cut_asurine = true
			cut_asurine_brick = true
			small_asurine_brick = true
			cut_crimsite = true
			polished_cut_crimsite = true
			cut_crimsite_brick = true
			small_crimsite_brick = true
			cut_limestone = true
			polished_cut_limestone = true
			cut_limestone_brick = true
			small_limestone_brick = true
			cut_ochrum = true
			polished_cut_ochrum = true
			cut_ochrum_brick = true
			small_ochrum_brick = true
			cut_scoria = true
			polished_cut_scoria = true
			cut_scoria_brick = true
			small_scoria_brick = true
			cut_scorchia = true
			polished_cut_scorchia = true
			cut_scorchia_brick = true
			small_scorchia_brick = true
			cut_veridium = true
			polished_cut_veridium = true
			cut_veridium_brick = true
			small_veridium_brick = true

		[types.cut_block_type.createdeco]
			dean_brick = true
			short_dean_brick = true
			tiled_dean_brick = true
			long_dean_brick = true
			corner_dean_brick = true
			cracked_dean_brick = true
			mossy_dean_brick = true
			pearl_brick = true
			short_pearl_brick = true
			tiled_pearl_brick = true
			long_pearl_brick = true
			corner_pearl_brick = true
			cracked_pearl_brick = true
			mossy_pearl_brick = true
			verdant_brick = true
			short_verdant_brick = true
			tiled_verdant_brick = true
			long_verdant_brick = true
			corner_verdant_brick = true
			cracked_verdant_brick = true
			mossy_verdant_brick = true
			short_red_brick = true
			tiled_red_brick = true
			long_red_brick = true
			corner_red_brick = true
			cracked_red_brick = true
			mossy_red_brick = true
			umber_brick = true
			short_umber_brick = true
			tiled_umber_brick = true
			long_umber_brick = true
			corner_umber_brick = true
			cracked_umber_brick = true
			mossy_umber_brick = true
			dusk_brick = true
			short_dusk_brick = true
			tiled_dusk_brick = true
			long_dusk_brick = true
			corner_dusk_brick = true
			cracked_dusk_brick = true
			mossy_dusk_brick = true
			scarlet_brick = true
			short_scarlet_brick = true
			tiled_scarlet_brick = true
			long_scarlet_brick = true
			corner_scarlet_brick = true
			cracked_scarlet_brick = true
			mossy_scarlet_brick = true
			blue_brick = true
			short_blue_brick = true
			tiled_blue_brick = true
			long_blue_brick = true
			corner_blue_brick = true
			cracked_blue_brick = true
			mossy_blue_brick = true

		[types.cut_block_type.tfmg]
			slag_bricks = true
			factory_floor = true
			hardened_planks = true
			concrete = true
			rebar_concrete = true
			white_concrete = true
			blue_concrete = true
			light_blue_concrete = true
			red_concrete = true
			green_concrete = true
			lime_concrete = true
			pink_concrete = true
			magenta_concrete = true
			yellow_concrete = true
			gray_concrete = true
			light_gray_concrete = true
			brown_concrete = true
			cyan_concrete = true
			purple_concrete = true
			orange_concrete = true
			black_concrete = true
			white_rebar_concrete = true
			blue_rebar_concrete = true
			light_blue_rebar_concrete = true
			red_rebar_concrete = true
			green_rebar_concrete = true
			lime_rebar_concrete = true
			pink_rebar_concrete = true
			magenta_rebar_concrete = true
			yellow_rebar_concrete = true
			gray_rebar_concrete = true
			light_gray_rebar_concrete = true
			brown_rebar_concrete = true
			cyan_rebar_concrete = true
			purple_rebar_concrete = true
			orange_rebar_concrete = true
			black_rebar_concrete = true
			asphalt = true
			cut_bauxite = true
			polished_cut_bauxite = true
			cut_bauxite_brick = true
			small_bauxite_brick = true
			cut_galena = true
			polished_cut_galena = true
			cut_galena_brick = true
			small_galena_brick = true

		[types.cut_block_type.quark]
			ancient_planks = true
			azalea_planks = true
			blossom_planks = true
			duskbound_block = true
			iron_plate = true
			rusty_iron_plate = true
			midori_block = true
			blue_nether_bricks = true
			sandstone_bricks = true
			red_sandstone_bricks = true
			soul_sandstone_bricks = true
			cobblestone_bricks = true
			mossy_cobblestone_bricks = true
			blackstone_bricks = true
			dirt_bricks = true
			netherrack_bricks = true
			limestone = true
			polished_limestone = true
			jasper = true
			polished_jasper = true
			shale = true
			polished_shale = true
			myalite = true
			polished_myalite = true
			permafrost = true
			permafrost_bricks = true
			raw_iron_bricks = true
			raw_gold_bricks = true
			raw_copper_bricks = true
			shingles = true
			white_shingles = true
			orange_shingles = true
			magenta_shingles = true
			light_blue_shingles = true
			yellow_shingles = true
			lime_shingles = true
			pink_shingles = true
			gray_shingles = true
			light_gray_shingles = true
			cyan_shingles = true
			purple_shingles = true
			blue_shingles = true
			brown_shingles = true
			green_shingles = true
			red_shingles = true
			black_shingles = true
			soul_sandstone = true
			cut_soul_sandstone = true
			smooth_soul_sandstone = true
			thatch = true
			calcite = true
			polished_calcite = true
			dripstone_block = true
			polished_dripstone = true
			tuff = true
			polished_tuff = true
			granite_bricks = true
			diorite_bricks = true
			andesite_bricks = true
			calcite_bricks = true
			dripstone_bricks = true
			tuff_bricks = true
			limestone_bricks = true
			jasper_bricks = true
			shale_bricks = true
			myalite_bricks = true

		[types.cut_block_type.supplementaries]
			fine_wood = true
			lapis_bricks = true
			ash_bricks = true
			stone_tile = true
			blackstone_tile = true

		[types.cut_block_type.mynethersdelight]
			powdery = true
			powdery_mosaic = true

		[types.cut_block_type.delightful]
			glow_jam_cookie_tile = true
			source_berry_cookie_tile = true

	[types.wood_type]

		[types.wood_type.domum_ornamentum]
			cactus = true
			cactus_extra = true

		[types.wood_type.ars_nouveau]
			archwood = true

		[types.wood_type.mynethersdelight]
			powdery = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.botania]
			livingwood = true
			dreamwood = true

		[types.wood_type.ad_astra]
			aeronos = true
			strophar = true
			glacian = true

		[types.wood_type.cataclysm]
			chorus = true

		[types.wood_type.beachparty]
			palm = true

	[types.cake]

		[types.cake.farmersrespite]
			coffee_cake = true

		[types.cake.mynethersdelight]
			magma_cake = true

		[types.cake.createaddition]
			chocolate_cake = true
			honey_cake = true

	[types.leaves_type]

		[types.leaves_type.fruitsdelight]
			pear = true
			hawberry = true
			lychee = true
			mango = true
			persimmon = true
			peach = true
			orange = true
			apple = true
			mangosteen = true
			bayberry = true
			kiwi = true
			fig = true
			durian = true

		[types.leaves_type.ad_astra]
			glacian = true

		[types.leaves_type.ars_nouveau]
			blue_archwood = true
			red_archwood = true
			purple_archwood = true
			green_archwood = true

		[types.leaves_type.culturaldelights]
			avocado = true
			fruiting_avocado = true

		[types.leaves_type.beachparty]
			palm = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.ars_elemental]
			yellow_archwood = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.handcrafted]
			counter = true
			corner_trim = true
			fancy_bed = true
			desk = true
			shelf = true
			cupboard = true
			dining_bench = true
			bench = true
			drawer = true
			pillar_trim = true
			side_table = true
			nightstand = true
			couch = true
			table = true
			chair = true

		[entries.wood_type.boatload]
			large_boat = true
			furnace_boat = true

		[entries.wood_type.redeco]
			stool = true
			polished_planks = true
			chair = true
			counter = true
			polished_slab = true
			crate = true
			display_case = true
			coffee_table = true
			side_table = true
			drawers = true
			cabinet_counter = true
			plank_fence = true
			table = true
			plank_gate = true
			sword_mount = true
			polished_stairs = true
			pedestal = true
			drawer_counter = true
			bench = true
			cabinet = true
			lattice = true
			shelf = true

		[entries.wood_type.refurbished_furniture]
			storage_cabinet = true
			storage_jar = true
			kitchen_cabinetry = true
			crate = true
			desk = true
			chair = true
			light_ceiling_fan = true
			cutting_board = true
			drawer = true
			table = true
			mail_box = true
			dark_ceiling_fan = true
			kitchen_sink = true
			toilet = true
			lattice_fence = true
			basin = true
			kitchen_drawer = true
			lattice_fence_gate = true
			bath = true
			kitchen_storage_cabinet = true

		[entries.wood_type.storagedelight]
			small_drawers = true
			single_door_cabinet = true
			cabinet_with_glass_doors = true
			drawer = true
			bookshelf_with_door = true
			glass_cabinet = true
			drawer_with_door = true
			drawer_with_books = true

		[entries.wood_type.create]
			window_pane = true
			window = true

		[entries.wood_type.storagedrawers]
			half_drawers_1 = true
			half_drawers_4 = true
			half_drawers_2 = true
			trim = true
			full_drawers_2 = true
			full_drawers_4 = true
			full_drawers_1 = true

		[entries.wood_type.quark]
			vertical_planks = true
			chest = true
			ladder = true
			hollow_log = true
			post = true
			trapped_chest = true
			bookshelf = true
			stripped_post = true
			vertical_slab = true

		[entries.wood_type.infinitybuttons]
			large_button = true
			plank_secret_button = true

		[entries.wood_type.hearth_and_home]
			sanded_wood = true
			lattice = true
			parquet = true
			vertical_trim = true
			trim = true

		[entries.wood_type.farmersdelight]
			cabinet = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

		[entries.leaves_type.refurbished_furniture]
			hedge = true

