
#Visual effect settings (client-side only)
["Render Settings"]
	#Quality of the main explosion fireball textures (glow, glow_2, sglow).
	#Lower quality (64p) can significantly improve performance on systems with less VRAM.
	#Requires a resource pack reload (F3+T) to apply the change.
	#Allowed Values: QUALITY_256, QUALITY_64
	glowTextureQuality = "QUALITY_64"
	#
	#Core explosion visual effects
	#Enables the main fiery glow particles (glow, glow_2, sglow). Disabling this can significantly improve performance.
	enableExplosionParticles = true
	#Enables the smoke trail that follows plasma sparks.
	enablePlasmaSmokeTrail = true
	#Enables the flash overlay effect on explosions.
	enableFlashEffect = true
	#Maximum opacity of the flash effect overlay. 0.0 = no flash, 1.0 = full opacity.
	#Range: 0.0 ~ 1.0
	flashMaxOpacity = 0.5
	#
	#Configuration for the electrical spark effects
	#Enables or disables the electrical line sparks that shoot out from explosions.
	enableLineSparks = true
	#Multiplier for the number of sparks generated by an explosion.
	#0.0 = no sparks, 1.0 = default amount, 2.0 = double amount.
	#Higher values can impact performance.
	#Range: 0.0 ~ 5.0
	lineSparkAmountMultiplier = 1.0
	#
	#Configuration for the ground dust cloud effect
	#Enables or disables the dust cloud effect from explosions.
	enableGroundDustEffect = true
	#Quality of the dust cloud effect. Affects particle count and duration.
	#Lower values can improve performance on weaker PCs.
	#0.0 = minimum particles, 1.0 = default quality.
	#Range: 0.0 ~ 1.0
	groundDustQuality = 1.0
	#Dust Propagation Quality. Controls how often dust particles check for the ground beneath them.
	#A value of 1 means every particle checks (highest quality, high performance cost).
	#A value of 10 means every 10th particle checks (default performance).
	#Range: 1 ~ 20
	groundDustRaycastFrequency = 10
	#
	#Configuration for the ground mist effect
	#Enables or disables the mist cloud effect from explosions.
	enableGroundMistEffect = true
	#Quality of the mist cloud effect. Affects particle count and duration.
	#Lower values can improve performance on weaker PCs.
	#0.0 = minimum particles, 1.0 = default quality.
	#Range: 0.0 ~ 1.0
	groundMistQuality = 1.0
	#Mist Propagation Quality. Controls how often mist particles check for the ground beneath them.
	#A value of 1 means every particle checks (highest quality, high performance cost).
	#A value of 10 means every 10th particle checks (default performance).
	#Range: 1 ~ 20
	groundMistRaycastFrequency = 10

#
#Camera shake settings
["Camera Shake"]
	#Enables or disables the camera shake effect from explosions.
	enableCameraShake = true
	#Amplifier for the camera shake intensity. 0.0 = no shake, 1.0 = default, 10.0 = maximum shake.
	#Range: 0.0 ~ 10.0
	cameraShakeAmplifier = 1.0

